#!/bin/sh

set -e

sed \
	-e '/\/interface\/wifi\//d' \
	-e '/\/interface\/wireless\//d' \
	-e 's|%TEMPL%|.capsman|' \
	-e '/^# NOT \/caps-man\/ #$/,/^# NOT \/caps-man\/ #$/d' \
	-e '/^# !!/,/^# !!/c # !! Do not edit this file, it is generated from template!' \
	< "${1}"
