#!/bin/sh

set -e

sed \
	-e '/\/caps-man\//d' \
	-e '/\/interface\/wireless\//d' \
	-e 's|%TEMPL%|.wifi|' \
	-e '/^# NOT \/interface\/wifi\/ #$/,/^# NOT \/interface\/wifi\/ #$/d' \
	-e '/^# !!/,/^# !!/c # !! Do not edit this file, it is generated from template!' \
	< "${1}"
