#!/bin/sh

set -e

sed \
	-e '/\/caps-man\//d' \
	-e '/\/interface\/wifi\//d' \
	-e 's|%TEMPL%|.local|' \
	-e '/^# NOT \/interface\/wireless\/ #$/,/^# NOT \/interface\/wireless\/ #$/d' \
	-e '/^# !!/,/^# !!/c # !! Do not edit this file, it is generated from template!' \
	< "${1}"
