#!rsc by RouterOS
# RouterOS script: capsman-download-packages.wifi
# Copyright (c) 2018-2026 Christian Hesse <mail@eworm.de>
#                         Michael Gisbers <michael@gisbers.de>
# https://rsc.eworm.de/COPYING.md
#
# requires RouterOS, version=7.22
#
# download and cleanup packages for CAP installation from CAPsMAN
# https://rsc.eworm.de/doc/capsman-download-packages.md
#
# !! Do not edit this file, it is generated from template!

# BEGIN GENERATED LANGUAGE DATA
# language, name=capsman-download-packages, schema=59f845c7f49406ecd939f7b0cebfb7f994f70400db30d8b136359720c88ab147
:global LanguageEnglish;
:if ([ :typeof $LanguageEnglish ] != "array") do={ :set LanguageEnglish ({}); }
:set ($LanguageEnglish->"capsman-download-packages.defaults") "No packages available, downloading default set.";
:set ($LanguageEnglish->"capsman-download-packages.directory.created") "Created directory at CAPsMAN package path ({path}). Please place your packages!";
:set ($LanguageEnglish->"capsman-download-packages.directory.failed") "Creating directory at CAPsMAN package path ({path}) failed!";
:set ($LanguageEnglish->"capsman-download-packages.path.undefined") "The CAPsMAN package path is not defined, can not download packages.";
# END GENERATED LANGUAGE DATA

:onerror Err {
  :global GlobalConfigReady; :global GlobalFunctionsReady;
  :retry { :if ($GlobalConfigReady != true || $GlobalFunctionsReady != true) \
      do={ :error ("Global config and/or functions not ready."); }; } delay=500ms max=50;
  :local ScriptName [ :jobname ];

  :global CleanFilePath;
  :global DownloadPackage;
  :global FileGet;
  :global LogPrint;
  :global Translate;
  :global MkDir;
  :global RmFile;
  :global ScriptLock;
  :global WaitFullyConnected;

  :if ([ $ScriptLock $ScriptName ] = false) do={
    :exit;
  }
  $WaitFullyConnected;

  :local PackagePath [ $CleanFilePath [ /interface/wifi/capsman/get package-path ] ];
  :local InstalledVersion [ /system/package/update/get installed-version ];
  :local Updated false;

  :if ([ :len $PackagePath ] = 0) do={
    $LogPrint warning $ScriptName [ $Translate "capsman-download-packages.path.undefined" ];
    :exit;
  }

  :if ([ $FileGet $PackagePath ] = false) do={
    :if ([ $MkDir $PackagePath ] = false) do={
      $LogPrint warning $ScriptName [ $Translate "capsman-download-packages.directory.failed" \
          ({ path=$PackagePath }) ];
      :exit;
    }
    $LogPrint info $ScriptName [ $Translate "capsman-download-packages.directory.created" \
        ({ path=$PackagePath }) ];
  }

  :foreach Package in=[ /file/find where type="package" \
        package-version!=$InstalledVersion name~("^" . $PackagePath) ] do={
    :local File [ /file/get $Package ];
    :if ($File->"package-architecture" = "mips") do={
      :set ($File->"package-architecture") "mipsbe";
    }
    :if ([ $DownloadPackage ($File->"package-name") $InstalledVersion \
         ($File->"package-architecture") $PackagePath ] = true) do={
      :set Updated true;
      $RmFile ($File->"name");
    }
  }

  :if ([ :len [ /file/find where type="package" name~("^" . $PackagePath) ] ] = 0) do={
    $LogPrint info $ScriptName [ $Translate "capsman-download-packages.defaults" ];
    :foreach Arch in={ "arm"; "arm64" } do={
      :local Packages { "arm"={ "routeros"; "wifi-qcom"; "wifi-qcom-ac" };
                      "arm64"={ "routeros"; "wifi-qcom" } };
      :foreach Package in=($Packages->$Arch) do={
        :if ([ $DownloadPackage $Package $InstalledVersion $Arch $PackagePath ] = true) do={
          :set Updated true;
        }
      }
    }
  }

  :if ($Updated = true) do={
    :local Scripts [ /system/script/find where source~"\n# provides: capsman-rolling-upgrade.wifi\r?\n" ];
    :if ([ :len $Scripts ] > 0) do={
      :foreach Script in=$Scripts do={
        /system/script/run $Script;
      }
    } else={
      /interface/wifi/capsman/remote-cap/upgrade [ find where version!=$InstalledVersion ];
    }
  }
} do={
  :global ExitOnError; $ExitOnError [ :jobname ] $Err;
}
