#!rsc by RouterOS
# RouterOS script: collect-wireless-mac.wifi
# Copyright (c) 2013-2026 Christian Hesse <mail@eworm.de>
# https://rsc.eworm.de/COPYING.md
#
# provides: dhcpv4-server-lease, order=40
# requires RouterOS, version=7.22
#
# collect wireless mac adresses in access list
# https://rsc.eworm.de/doc/collect-wireless-mac.md
#
# !! Do not edit this file, it is generated from template!

# BEGIN GENERATED LANGUAGE DATA
# language, name=collect-wireless-mac, schema=70ad56ad671ad178315877f3d03eaddd505e04060e94d4c635cd2ebab32adee9
:global LanguageEnglish;
:if ([ :typeof $LanguageEnglish ] != "array") do={ :set LanguageEnglish ({}); }
:set ($LanguageEnglish->"collect-wireless-mac.device.gone") "Device already gone... Ignoring.";
:set ($LanguageEnglish->"collect-wireless-mac.dns.missing") "no dns name";
:set ($LanguageEnglish->"collect-wireless-mac.first.seen") "MAC address {mac} ({vendor}, {hostname}) first seen on {date} connected to SSID {ssid}, interface {interface}";
:set ($LanguageEnglish->"collect-wireless-mac.hostname.missing") "no hostname";
:set ($LanguageEnglish->"collect-wireless-mac.known") "MAC address {mac} already known: {comment}";
:set ($LanguageEnglish->"collect-wireless-mac.label.address") "Address";
:set ($LanguageEnglish->"collect-wireless-mac.label.controller") "Controller";
:set ($LanguageEnglish->"collect-wireless-mac.label.date") "Date";
:set ($LanguageEnglish->"collect-wireless-mac.label.dns") "DNS name";
:set ($LanguageEnglish->"collect-wireless-mac.label.hostname") "Hostname";
:set ($LanguageEnglish->"collect-wireless-mac.label.interface") "Interface";
:set ($LanguageEnglish->"collect-wireless-mac.label.mac") "MAC";
:set ($LanguageEnglish->"collect-wireless-mac.label.ssid") "SSID";
:set ($LanguageEnglish->"collect-wireless-mac.label.vendor") "Vendor";
:set ($LanguageEnglish->"collect-wireless-mac.lease.missing") "no dhcp lease";
:set ($LanguageEnglish->"collect-wireless-mac.mac.missing") "No mac address available... Ignoring.";
:set ($LanguageEnglish->"collect-wireless-mac.marker.added") "Added disabled access-list entry with comment '--- collected above ---'.";
:set ($LanguageEnglish->"collect-wireless-mac.message") "A device with unknown MAC address connected to {ssid} on {identity}.\0A\0A";
:set ($LanguageEnglish->"collect-wireless-mac.subject") "{mac} connected to {ssid}";
:set ($LanguageEnglish->"global-config.not.ready") "Global config and/or functions not ready.";
:global GlobalNotReadyMessage;
:if ([ :typeof $GlobalNotReadyMessage ] != "str") do={
  :set GlobalNotReadyMessage ($LanguageEnglish->"global-config.not.ready");
}
# END GENERATED LANGUAGE DATA

:onerror Err {
  :global GlobalConfigReady; :global GlobalFunctionsReady;
  :global GlobalNotReadyMessage;
  :retry { :if ($GlobalConfigReady != true || $GlobalFunctionsReady != true) \
      do={ :error $GlobalNotReadyMessage; }; } delay=500ms max=50;
  :local ScriptName [ :jobname ];

  :global Identity;

  :global EitherOr;
  :global FormatLine;
  :global FormatMultiLines;
  :global GetMacVendor;
  :global LogPrint;
  :global Translate;
  :global ScriptLock;
  :global SendNotification2;
  :global SymbolForNotification;

  :if ([ $ScriptLock $ScriptName 10 ] = false) do={
    :exit;
  }

  :if ([ :len [ /interface/wifi/access-list/find where comment="--- collected above ---" disabled ] ] = 0) do={
    /interface/wifi/access-list/add comment="--- collected above ---" disabled=yes;
    $LogPrint warning $ScriptName [ $Translate "collect-wireless-mac.marker.added" ];
  }
  :local PlaceBefore ([ /interface/wifi/access-list/find where comment="--- collected above ---" disabled ]->0);

  :foreach Reg in=[ /interface/wifi/registration-table/find ] do={
    :local RegVal;
    :do {
      :set RegVal [ /interface/wifi/registration-table/get $Reg ];
    } on-error={
      $LogPrint debug $ScriptName [ $Translate "collect-wireless-mac.device.gone" ];
    }

    :if ([ :len ($RegVal->"mac-address") ] > 0) do={
      :local AccessList ([ /interface/wifi/access-list/find where mac-address=($RegVal->"mac-address") ]->0);
      :if ([ :len $AccessList ] > 0) do={
        :local AccessComment [ /interface/wifi/access-list/get $AccessList comment ];
        $LogPrint debug $ScriptName [ $Translate "collect-wireless-mac.known" \
            ({ mac=($RegVal->"mac-address"); comment=$AccessComment }) ];
      }

      :if ([ :len $AccessList ] = 0) do={
        :local Address [ $Translate "collect-wireless-mac.lease.missing" ];
        :local DnsName [ $Translate "collect-wireless-mac.lease.missing" ];
        :local HostName [ $Translate "collect-wireless-mac.lease.missing" ];
        :local Lease ([ /ip/dhcp-server/lease/find where active-mac-address=($RegVal->"mac-address") dynamic=yes status=bound ]->0);
        :if ([ :len $Lease ] > 0) do={
          :set Address [ /ip/dhcp-server/lease/get $Lease active-address ];
          :set HostName [ $EitherOr [ /ip/dhcp-server/lease/get $Lease host-name ] [ $Translate "collect-wireless-mac.hostname.missing" ] ];
          :set DnsName [ $Translate "collect-wireless-mac.dns.missing" ];
          :local DnsRec ([ /ip/dns/static/find where address=$Address ]->0);
          :if ([ :len $DnsRec ] > 0) do={
            :set DnsName ({ [ /ip/dns/static/get $DnsRec name ] });
            :foreach CName in=[ /ip/dns/static/find where type=CNAME cname=($DnsName->0) ] do={
              :set DnsName ($DnsName, [ /ip/dns/static/get $CName name ]);
            }
          }
        }
        :local DateTime ([ /system/clock/get date ] . " " . [ /system/clock/get time ]);
        :local Vendor [ $GetMacVendor ($RegVal->"mac-address") ];
        :local Message [ $Translate "collect-wireless-mac.first.seen" \
            ({ mac=($RegVal->"mac-address"); vendor=[ :tostr $Vendor ]; hostname=$HostName; date=$DateTime; ssid=[ :tostr ($RegVal->"ssid") ]; interface=($RegVal->"interface") }) ];
        $LogPrint info $ScriptName $Message;
        /interface/wifi/access-list/add place-before=$PlaceBefore comment=$Message mac-address=($RegVal->"mac-address") disabled=yes;
        $SendNotification2 ({ origin=$ScriptName; silent=false; \
          subject=([ $SymbolForNotification "mobile-phone" ] . [ $Translate "collect-wireless-mac.subject" \
              ({ mac=($RegVal->"mac-address"); ssid=[ :tostr ($RegVal->"ssid") ] }) ]); \
          message=([ $Translate "collect-wireless-mac.message" \
              ({ ssid=[ :tostr ($RegVal->"ssid") ]; identity=$Identity }) ] . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.controller" ] $Identity ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.interface" ] ($RegVal->"interface") ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.ssid" ] ($RegVal->"ssid") ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.mac" ] ($RegVal->"mac-address") ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.vendor" ] $Vendor ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.hostname" ] $HostName ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.address" ] $Address ] . "\n" . \
            [ $FormatMultiLines [ $Translate "collect-wireless-mac.label.dns" ] $DnsName ] . "\n" . \
            [ $FormatLine [ $Translate "collect-wireless-mac.label.date" ] $DateTime ]) });
      }
    } else={
      $LogPrint debug $ScriptName [ $Translate "collect-wireless-mac.mac.missing" ];
    }
  }
} do={
  :global ExitOnError; $ExitOnError [ :jobname ] $Err;
}
