#!rsc by RouterOS
# RouterOS script: daily-psk.capsman
# Copyright (c) 2013-2026 Christian Hesse <mail@eworm.de>
#                         Michael Gisbers <michael@gisbers.de>
# https://rsc.eworm.de/COPYING.md
#
# requires RouterOS, version=7.22
#
# update daily PSK (pre shared key)
# https://rsc.eworm.de/doc/daily-psk.md
#
# !! Do not edit this file, it is generated from template!

# BEGIN GENERATED LANGUAGE DATA
# language, name=daily-psk, schema=64d2ff049c113163d9a5b4847306ad5ac276859115f25bfe3d397cc8b24a1ea0
:global LanguageEnglish;
:if ([ :typeof $LanguageEnglish ] != "array") do={ :set LanguageEnglish ({}); }
:set ($LanguageEnglish->"daily-psk.date") "Date";
:set ($LanguageEnglish->"daily-psk.message") "This is the daily PSK on {identity}:\0A\0A{ssid}\0A{psk}\0A{date}\0A\0AA client device specific rule must not exist!";
:set ($LanguageEnglish->"daily-psk.sent") "Already sent a mail for SSID {ssid}, skipping.";
:set ($LanguageEnglish->"daily-psk.subject") "daily PSK {ssid}";
:set ($LanguageEnglish->"daily-psk.updating") "Updating daily PSK for '{ssid}' to '{psk}' (was '{previous}')";
:set ($LanguageEnglish->"global-config.not.ready") "Global config and/or functions not ready.";
:global GlobalNotReadyMessage;
:if ([ :typeof $GlobalNotReadyMessage ] != "str") do={
  :set GlobalNotReadyMessage ($LanguageEnglish->"global-config.not.ready");
}
# END GENERATED LANGUAGE DATA

:onerror Err {
  :global GlobalConfigReady; :global GlobalFunctionsReady;
  :global GlobalNotReadyMessage;
  :retry { :if ($GlobalConfigReady != true || $GlobalFunctionsReady != true) \
      do={ :error $GlobalNotReadyMessage; }; } delay=500ms max=50;
  :local ScriptName [ :jobname ];

  :global DailyPskMatchComment;
  :global DailyPskQrCodeUrl;
  :global Identity;

  :global FormatLine;
  :global LogPrint;
  :global Translate;
  :global ScriptLock;
  :global SendNotification2;
  :global SymbolForNotification;
  :global WaitForFile;
  :global WaitFullyConnected;

  :if ([ $ScriptLock $ScriptName ] = false) do={
    :exit;
  }
  $WaitFullyConnected;

  # return pseudo-random string for PSK
  :local GeneratePSK do={
    :local Date [ :tostr $1 ];

    :global DailyPskSecrets;

    :global ParseDate;

    :set Date [ $ParseDate $Date ];

    :local A ((14 - ($Date->"month")) / 12);
    :local B (($Date->"year") - $A);
    :local C (($Date->"month") + 12 * $A - 2);
    :local WeekDay (7000 + ($Date->"day") + $B + ($B / 4) - ($B / 100) + ($B / 400) + ((31 * $C) / 12));
    :set WeekDay ($WeekDay - (($WeekDay / 7) * 7));

    :return (($DailyPskSecrets->0->(($Date->"day") - 1)) . \
      ($DailyPskSecrets->1->(($Date->"month") - 1)) . \
      ($DailyPskSecrets->2->$WeekDay));
  }

  :local Seen ({});
  :local Date [ /system/clock/get date ];
  :local NewPsk [ $GeneratePSK $Date ];

  :foreach AccList in=[ /caps-man/access-list/find where comment~$DailyPskMatchComment ] do={
    :local SsidRegExp [ /caps-man/access-list/get $AccList ssid-regexp ];
    :local Configuration ([ /caps-man/configuration/find where ssid~$SsidRegExp ]->0);
    :local Ssid [ /caps-man/configuration/get $Configuration ssid ];
    :local OldPsk [ /caps-man/access-list/get $AccList private-passphrase ];
    :local Skip 0;

    :if ($NewPsk != $OldPsk) do={
      $LogPrint info $ScriptName [ $Translate "daily-psk.updating" \
          ({ ssid=$Ssid; psk=$NewPsk; previous=$OldPsk }) ];
      /caps-man/access-list/set $AccList private-passphrase=$NewPsk;

      :if ([ :len [ /caps-man/actual-interface-configuration/find where configuration.ssid=$Ssid !disabled ] ] > 0) do={
        :if ($Seen->$Ssid = 1) do={
          $LogPrint debug $ScriptName [ $Translate "daily-psk.sent" \
              ({ ssid=$Ssid }) ];
        } else={
          :local Link ($DailyPskQrCodeUrl . \
              "?scale=8&level=1&ssid=" . [ :convert to=url $Ssid ] . "&pass=" . [ :convert to=url $NewPsk ]);
          $SendNotification2 ({ origin=$ScriptName; silent=true; \
            subject=([ $SymbolForNotification "calendar" ] . [ $Translate "daily-psk.subject" \
                ({ ssid=$Ssid }) ]); \
            message=([ $Translate "daily-psk.message" \
                ({ identity=$Identity; ssid=[ $FormatLine "SSID" $Ssid 8 ]; psk=[ $FormatLine "PSK" $NewPsk 8 ]; date=[ $FormatLine [ $Translate "daily-psk.date" ] $Date 8 ] }) ]); link=$Link });
          :set ($Seen->$Ssid) 1;
        }
      }
    }
  }
} do={
  :global ExitOnError; $ExitOnError [ :jobname ] $Err;
}
