#!rsc by RouterOS
# RouterOS script: hotspot-to-wpa-lease.wifi
# Copyright (c) 2019-2026 Christian Hesse <mail@eworm.de>
# https://rsc.eworm.de/COPYING.md
#
# provides: dhcpv4-server-lease, order=40
# requires RouterOS, version=7.22
# requires device-mode, hotspot
#
# add private WPA passphrase after hotspot login
# https://rsc.eworm.de/doc/hotspot-to-wpa.md
#
# !! Do not edit this file, it is generated from template!

:onerror Err {
  :global GlobalConfigReady; :global GlobalFunctionsReady;
  :retry { :if ($GlobalConfigReady != true || $GlobalFunctionsReady != true) \
      do={ :error ("Global config and/or functions not ready."); }; } delay=500ms max=50;
  :local ScriptName [ :jobname ];

  :global EitherOr;
  :global LogPrint;
  :global ParseKeyValueStore;
  :global ScriptLock;

  :if ([ $ScriptLock $ScriptName ] = false) do={
    :exit;
  }

  :if ([ :len [ /interface/wifi/access-list/find where comment="--- hotspot-to-wpa above ---" disabled ] ] = 0) do={
    /interface/wifi/access-list/add comment="--- hotspot-to-wpa above ---" disabled=yes;
    $LogPrint warning $ScriptName ("Added disabled access-list entry with comment '--- hotspot-to-wpa above ---'.");
  }
  :local PlaceBefore ([ /interface/wifi/access-list/find where comment="--- hotspot-to-wpa above ---" disabled ]->0);

  :foreach Lease in=[ /ip/dhcp-server/lease/find where !dynamic disabled comment~"\\bhotspot-to-wpa\\b" ] do={
    :local LeaseVal [ $ParseKeyValueStore [ /ip/dhcp-server/lease/get $Lease comment ] ];
    /ip/dhcp-server/lease/remove $Lease;

    :if (($LeaseVal->"hotspot-to-wpa") != true) do={
      :continue;
    }

    :local Date [ /system/clock/get date ];
    :local UserVal ({});
    :if ([ :len [ /ip/hotspot/user/find where name=($LeaseVal->"username") ] ] > 0) do={
      :set UserVal [ /ip/hotspot/user/get [ find where name=($LeaseVal->"username") ] ];
    }
    :local UserInfo [ $ParseKeyValueStore ($UserVal->"comment") ];

    :if ([ :len [ /interface/wifi/access-list/find where \
        comment=("hotspot-to-wpa template " . $LeaseVal->"hotspot") disabled ] ] = 0) do={
      /interface/wifi/access-list/add comment=("hotspot-to-wpa template " . $LeaseVal->"hotspot") disabled=yes place-before=$PlaceBefore;
      $LogPrint warning $ScriptName ("Added template in access-list for hotspot '" . $LeaseVal->"hotspot" . "'.");
    }
    :local Template [ /interface/wifi/access-list/get ([ find where \
        comment=("hotspot-to-wpa template " . $LeaseVal->"hotspot") disabled ]->0) ];

    $LogPrint info $ScriptName ("Adding/updating access-list entry for mac address " . $LeaseVal->"mac-address" . \
      " (user " . $LeaseVal->"username" . ").");
    /interface/wifi/access-list/remove [ find where mac-address=($LeaseVal->"mac-address") comment~"^hotspot-to-wpa: " ];
    /interface/wifi/access-list/add passphrase=($UserVal->"password") ssid-regexp="-wpa\$" \
        mac-address=($LeaseVal->"mac-address") comment=("hotspot-to-wpa: " . $LeaseVal->"username" . \
        ", " . $LeaseVal->"mac-address" . ", " . $Date) action=reject place-before=$PlaceBefore;

    :local Entry [ /interface/wifi/access-list/find where mac-address=($LeaseVal->"mac-address") \
        comment=("hotspot-to-wpa: " . $LeaseVal->"username" . ", " . $LeaseVal->"mac-address" . ", " . $Date) ];
    :set ($Template->"private-passphrase") ($Template->"passphrase");
    :local PrivatePassphrase [ $EitherOr ($UserInfo->"private-passphrase") ($Template->"private-passphrase") ];
    :if ([ :len $PrivatePassphrase ] > 0) do={
      :if ($PrivatePassphrase = "ignore") do={
        /interface/wifi/access-list/set $Entry !passphrase;
      } else={
        /interface/wifi/access-list/set $Entry passphrase=$PrivatePassphrase;
      }
    }
    :local SsidRegexp [ $EitherOr ($UserInfo->"ssid-regexp") ($Template->"ssid-regexp") ];
    :if ([ :len $SsidRegexp ] > 0) do={
      /interface/wifi/access-list/set $Entry ssid-regexp=$SsidRegexp;
    }
    :local VlanId [ $EitherOr ($UserInfo->"vlan-id") ($Template->"vlan-id") ];
    :if ([ :len $VlanId ] > 0) do={
      /interface/wifi/access-list/set $Entry vlan-id=$VlanId;
    }

    :delay 2s;
    /interface/wifi/access-list/set $Entry action=accept;
  }
} do={
  :global ExitOnError; $ExitOnError [ :jobname ] $Err;
}
