#!rsc by RouterOS
# RouterOS script: hotspot-to-wpa-cleanup.capsman
# Copyright (c) 2021-2026 Christian Hesse <mail@eworm.de>
# https://rsc.eworm.de/COPYING.md
#
# provides: dhcpv4-server-lease, order=80
# requires RouterOS, version=7.22
# requires device-mode, hotspot
#
# manage and clean up private WPA passphrase after hotspot login
# https://rsc.eworm.de/doc/hotspot-to-wpa.md
#
# !! Do not edit this file, it is generated from template!

# BEGIN GENERATED LANGUAGE DATA
# language, name=hotspot-to-wpa-cleanup, schema=1ebc7ea0f3bc0cc65554da860eb4b0739adc55a3f127030c7d8a1c780e722a35
:global LanguageEnglish;
:if ([ :typeof $LanguageEnglish ] != "array") do={ :set LanguageEnglish ({}); }
:set ($LanguageEnglish->"hotspot-to-wpa-cleanup.connected") "Client with mac address {mac} connected to WPA, making lease static.";
:set ($LanguageEnglish->"hotspot-to-wpa-cleanup.disconnected") "Client with mac address {mac} did not connect to WPA, removing from access list.";
:set ($LanguageEnglish->"hotspot-to-wpa-cleanup.expired") "Client with mac address {mac} was not seen for {elapsed}, removing.";
:set ($LanguageEnglish->"global-config.not.ready") "Global config and/or functions not ready.";
:global GlobalNotReadyMessage;
:if ([ :typeof $GlobalNotReadyMessage ] != "str") do={
  :set GlobalNotReadyMessage ($LanguageEnglish->"global-config.not.ready");
}
# END GENERATED LANGUAGE DATA

:onerror Err {
  :global GlobalConfigReady; :global GlobalFunctionsReady;
  :global GlobalNotReadyMessage;
  :retry { :if ($GlobalConfigReady != true || $GlobalFunctionsReady != true) \
      do={ :error $GlobalNotReadyMessage; }; } delay=500ms max=50;
  :local ScriptName [ :jobname ];

  :global EitherOr;
  :global LogPrint;
  :global Translate;
  :global ParseKeyValueStore;
  :global ScriptLock;

  :if ([ $ScriptLock $ScriptName 10 ] = false) do={
    :exit;
  }

  :local DHCPServers ({});
  :foreach Server in=[ /ip/dhcp-server/find where comment~"hotspot-to-wpa" ] do={
    :local ServerVal [ /ip/dhcp-server/get $Server ]
    :local ServerInfo [ $ParseKeyValueStore ($ServerVal->"comment") ];
    :if (($ServerInfo->"hotspot-to-wpa") = "wpa") do={
      :set ($DHCPServers->($ServerVal->"name")) \
        [ :totime [ $EitherOr ($ServerInfo->"timeout") 4w ] ];
    }
  }

  :foreach Client in=[ /caps-man/registration-table/find where comment~"^hotspot-to-wpa:" ] do={
    :local ClientVal [ /caps-man/registration-table/get $Client ];
    :foreach Lease in=[ /ip/dhcp-server/lease/find where dynamic \
        mac-address=($ClientVal->"mac-address") ] do={
      :if (($DHCPServers->[ /ip/dhcp-server/lease/get $Lease server ]) > 0s) do={
        $LogPrint info $ScriptName [ $Translate "hotspot-to-wpa-cleanup.connected" \
            ({ mac=($ClientVal->"mac-address") }) ];
        /ip/dhcp-server/lease/make-static $Lease;
        /ip/dhcp-server/lease/set comment=($ClientVal->"comment") $Lease;
      }
    }
  }

  :foreach Client in=[ /caps-man/access-list/find where comment~"^hotspot-to-wpa:" \
      !(comment~[ /system/clock/get date ]) mac-address ] do={
    :local ClientVal [ /caps-man/access-list/get $Client ];
    :if ([ :len [ /ip/dhcp-server/lease/find where !dynamic comment~"^hotspot-to-wpa:" \
         mac-address=($ClientVal->"mac-address") ] ] = 0) do={
      $LogPrint info $ScriptName [ $Translate "hotspot-to-wpa-cleanup.disconnected" \
          ({ mac=($ClientVal->"mac-address") }) ];
      /caps-man/access-list/remove $Client;
    }
  }

  :foreach Server,Timeout in=$DHCPServers do={
    :local TimeoutExtra ($Timeout + [ /system/clock/get time ]);
    :foreach Lease in=[ /ip/dhcp-server/lease/find where !dynamic status="waiting" \
        server=$Server last-seen>$TimeoutExtra comment~"^hotspot-to-wpa:" ] do={
      :local LeaseVal [ /ip/dhcp-server/lease/get $Lease ];
      $LogPrint info $ScriptName [ $Translate "hotspot-to-wpa-cleanup.expired" \
          ({ mac=($LeaseVal->"mac-address"); elapsed=($LeaseVal->"last-seen") }) ];
      /caps-man/access-list/remove [ find where comment~"^hotspot-to-wpa:" \
        mac-address=($LeaseVal->"mac-address") ];
      /ip/dhcp-server/lease/remove $Lease;
    }
  }
} do={
  :global ExitOnError; $ExitOnError [ :jobname ] $Err;
}
