GENERATE = *.capsman *.local

all: $(GENERATE) README.html

README.html: README.md
	markdown README.md > README.html

%.local: *.template Makefile
	sed -e '/\/ caps-man/d' -e 's|%PATH%|interface wireless|' -e 's|%TEMPL%|$(suffix $@)|' \
		-e '/^# !!/,/^# !!/c # !! Do not edit this file, it is generated from template!' \
		< $(basename $@).template > $@

%.capsman: *.template Makefile
	sed -e '/\/ interface wireless/d' -e 's/%PATH%/caps-man/' -e 's/%TEMPL%/$(suffix $@)/' \
		-e '/^# !!/,/^# !!/c # !! Do not edit this file, it is generated from template!' \
		< $(basename $@).template > $@
